"""Adding threshold column

Revision ID: 3a03c6120a38
Revises: dcfa013ab9b1
Create Date: 2025-07-20 14:07:56.568187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a03c6120a38'
down_revision: Union[str, Sequence[str], None] = 'dcfa013ab9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('buy_threshold', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sell_threshold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sell_threshold')
    op.drop_column('users', 'buy_threshold')
    # ### end Alembic commands ###
